APP:
  APP_NAME: "dnevnik-rg"
  APP_VERSION: "1.0"
  DEPLOY: "localhost:8000"
  JWT_SECRET: "YTNjNzcwNTctODA4MC00YTc4LThmNzctODVmMDk1NzMyMmRm"
HTTP:
  HTTP_HOST: "0.0.0.0"
  HTTP_PORT: "8000"
POSTGRES:
  shard1:
    PG_NAME: "dnevnik_rg"
    PG_HOST: "pgsql.prod"
    PG_PORT: "5432"
    PG_USER: "dnevnik_rg_user_prod"
    PG_PASSWORD: "NDY1Yzg2YjQtNDQzMy00OWQzLTkxODgtMGNkNmQ3Nzc4MmMx"
TG_BOTS:
  TECH_BOT:
    TG_TECH_TOKEN: "6902343077:AAERsYxj7p-_eiSLL4cFPaX90yWi_cY1jdQ"