version:
  "3.8"

services:
  #######
  # STAGE
  #######
  service-stage:
    build:
      context: .
      target: final
    environment:
      BUILD_ENV: "stage"
    ports:
      - "8000:8000"

  ######
  # PROD
  ######
  service-prod:
    build:
      context: .
      target: final
    environment:
      BUILD_ENV: "prod"
    ports:
      - "8001:8000"