APP:
  APP_NAME: "dnevnik-rg"
  APP_VERSION: "1.0"
  DEPLOY: "localhost:8000"
  JWT_SECRET: "N2U3MmI1NTktZmUxOS00MzQ3LTk2YTQtM2Q0MjVlODc2OWIy"
HTTP:
  HTTP_HOST: "0.0.0.0"
  HTTP_PORT: "8000"
POSTGRES:
  shard1:
    PG_NAME: "dnevnik_rg",
    PG_HOST: "pgsql.stage"
    PG_PORT: "5432"
    PG_USER: "dnevnik_rg_user_stage"
    PG_PASSWORD: "NzZiMGE3YWUtYzFjNy00ZTI2LWIyY2ItMzFkOGJhNDA5OWJk"
TG_BOTS:
  TECH_BOT:
    TG_TECH_TOKEN: "6902343077:AAERsYxj7p-_eiSLL4cFPaX90yWi_cY1jdQ"