APP:
  APP_NAME: "dnevnik-rg"
  APP_VERSION: "1.0"
  DEPLOY: "localhost:8000"
  JWT_SECRET: "fb72b59c761f46c0690fdff1e15"
HTTP:
  HTTP_HOST: "localhost"
  HTTP_PORT: "8000"
POSTGRES:
  shard1:
    PG_NAME: "dnevnik-rg.shard-1"
    PG_HOST: "localhost"
    PG_PORT: "5588"
    PG_USER: "30c128f7"
    PG_PASSWORD: "058cb8ee6a01b88f"
    PG_DRIVER: "pq"
  shard2:
    PG_NAME: "dnevnik-rg.shard-2"
    PG_HOST: "localhost"
    PG_PORT: "5589"
    PG_USER: "30c128f7"
    PG_PASSWORD: "058cb8ee6a01b88f"
    PG_DRIVER: "pq"
  shard3:
    PG_NAME: "dnevnik-rg.shard-3"
    PG_HOST: "localhost"
    PG_PORT: "5590"
    PG_USER: "30c128f7"
    PG_PASSWORD: "058cb8ee6a01b88f"
    PG_DRIVER: "pq"
TG_BOTS:
  TECH_BOT:
    TG_TECH_TOKEN: "6902343077:AAERsYxj7p-_eiSLL4cFPaX90yWi_cY1jdQ"