APP:
  APP_NAME: "dnevnik-rg"
  APP_VERSION: "1.0"
  DEPLOY: "localhost:8000"
  JWT_SECRET: "fb72b59c761f46c0690fdff1e15"
HTTP:
  HTTP_HOST: "localhost"
  HTTP_PORT: "8000"
POSTGRES:
  PG_HOST: "localhost"
  PG_PORT: "5588"
  PG_USER: "30c128f7"
  PG_PASSWORD: "058cb8ee6a01b88f"
  PG_NAME: "dnevnik-rg"
  PG_DRIVER: "pq"