app:
  app_name: "dnevnik-rg"
  app_version: "1.0"
  deploy: "localhost:8000"
http:
  http_host: "0.0.0.0"
  http_port: "8000"
postgres:
  postgres_dbname: "dnevnik_rg"
  postgres_host: "localhost"
  postgres_port: "5589"
vault_config:
  vault_host: "host.docker.internal"
  vault_port: "8200"

vault:
  postgres:
    path: "/v1/secret/data/postgres"
    username_variable: "postgres_username"
    password_variable: "postgres_password"
  app:
    path: "/v1/secret/data/app"
    jwt_secret_variable: "jwt_secret"
  telebot:
    path: "/v1/secret/data/telebot"
    token_variable: "token"